menu: Menu.c Survivor.c TurnQueue.c GameManager.c EquipmentCards.c GameBoard.c Equipment.c
	gcc -g -o Menu Menu.c Survivor.c TurnQueue.c GameManager.c EquipmentCards.c GameBoard.c Equipment.c

all: Menu

clean:
	rm Menu
